@url=http://localhost:3002
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhZG1pbnJpY2FAZ21haWwuY29tIiwidXNlclR5cGUiOiJBZG1pbiIsImlhdCI6MTYzOTU4MDY0MCwiZXhwIjoxNjM5NjY3MDQwfQ.XwPfmAVdz07hM9T_cCvDTUKM6Jo8FEIMhoM_uoiP3sk

### Create user
POST {{url}}/users
Content-Type: application/json

{
    "name": "Admin",
    "email": "adminrica@gmail.com",
    "password": "1234",
    "userType": "Admin"
}

//"userType": "Admin"

### Get all users
GET {{url}}/users
Authorization: {{token}}

### Get by ID
GET {{url}}/users/2
Authorization: {{token}}

### Delete user (by Id)
DELETE {{url}}/users/3
Authorization: {{token}}
